<?php
/**
 * The homepage template file.
 *
 * @package WordPress
 * @subpackage ChurchThemes
 *
 ===================================================================================================
 WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

 To make it easy to update your theme, you should not edit this file. Instead, you should create a
 Child Theme first. This will ensure your template changes are not lost when updating the theme.

 You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

 You have been warned! :)
 ===================================================================================================
 */

get_header() ?>
		<div id="wrapper3" class="container_12 grid-container">
			<div class="grid_4 grid-33 alpha">
			    <!-- Custom widget made to show only the announcements -->
				<div class="home_widget">		
					<h3>Derni&eacute;res annonces</h3>
					<ul>
						<?php
						$args = array( 'posts_per_page' => 5, 'orderby' => 'post_date', 'category' => 11 );
						$rand_posts = get_posts( $args );
						foreach ( $rand_posts as $post ) : 
						  setup_postdata( $post ); ?>
							<li><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a> - <span class="post_date"><?php the_date() ?></span></li>
						<?php endforeach; 
						wp_reset_postdata(); ?>
					</ul>
				</div>
				<?php dynamic_sidebar('Homepage Left') ?>
			</div>
			<div class="grid_4 grid-33">
				<?php dynamic_sidebar('Homepage Center') ?>
			</div>
			<div class="grid_4 grid-33 omega">
				<?php dynamic_sidebar('Homepage Right') ?>
			</div>
		</div>
<?php get_footer() ?>
